

info.configuration: Read From Config Service application.properties

logging.level.com.netflix.discovery: 'OFF'
logging.level.org.springframework.cloud: 'DEBUG'

server:
  tomcat:
    compression: on

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672

    sleuth:
      sampler:
        probability: 1
  zipkin:
    type: web
    base-url: http://zipkin-server:9411/
